In [1]:
import numpy as np
import cv2 as cv
import glob

In [2]:
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [3]:
# Define the chess board rows and columns
rows = 11
cols = 8

In [4]:
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((rows*cols,3), np.float32)
objp[:,:2] = np.mgrid[0:rows,0:cols].T.reshape(-1,2)
 
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [5]:
images = glob.glob('*.bmp')

In [6]:
import cv2
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
 
    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (rows, cols), None)
 
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
 
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
 
        # Draw and display the corners
        cv.drawChessboardCorners(img, (rows, cols), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(500)

In [7]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [8]:
mtx

array([[2.51871226e+03, 0.00000000e+00, 1.08045518e+03],
       [0.00000000e+00, 2.51898572e+03, 8.10445150e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [9]:
dist

array([[-7.73529233e-02,  1.60282894e-01,  7.23371903e-05,
         1.75367878e-03, -4.47502729e-01]])

In [10]:
rvecs

(array([[ 0.08408605],
        [-0.22289696],
        [ 0.34257825]]),
 array([[-0.13263158],
        [ 0.03787585],
        [ 0.08311908]]))

In [11]:
tvecs

(array([[-0.92128639],
        [-4.70643807],
        [32.50237739]]),
 array([[-1.45624132],
        [-3.14147107],
        [36.32171909]]))

In [12]:
corners

array([[[ 979.62915,  592.7919 ]],

       [[1048.5057 ,  597.94507]],

       [[1117.7013 ,  603.28406]],

       [[1187.0565 ,  608.66907]],

       [[1256.5367 ,  613.9695 ]],

       [[1326.0482 ,  619.4644 ]],

       [[1395.795  ,  624.9137 ]],

       [[1465.6465 ,  630.35016]],

       [[1535.518  ,  635.7168 ]],

       [[1605.4448 ,  641.28705]],

       [[1675.4097 ,  646.8596 ]],

       [[ 973.2992 ,  660.6599 ]],

       [[1042.3809 ,  665.9693 ]],

       [[1111.8807 ,  671.3873 ]],

       [[1181.4454 ,  676.98206]],

       [[1251.2025 ,  682.40027]],

       [[1321.0782 ,  687.7247 ]],

       [[1391.0511 ,  693.29877]],

       [[1461.0896 ,  698.9029 ]],

       [[1531.2657 ,  704.4069 ]],

       [[1601.4307 ,  709.93   ]],

       [[1671.622  ,  715.5236 ]],

       [[ 966.87286,  729.0249 ]],

       [[1036.3387 ,  734.5553 ]],

       [[1106.0409 ,  740.0329 ]],

       [[1175.9144 ,  745.59644]],

       [[1245.8661 ,  751.1587 ]],

       [[1315.9698 ,  756.66

In [13]:
objpoints

[array([[ 0.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 2.,  0.,  0.],
        [ 3.,  0.,  0.],
        [ 4.,  0.,  0.],
        [ 5.,  0.,  0.],
        [ 6.,  0.,  0.],
        [ 7.,  0.,  0.],
        [ 8.,  0.,  0.],
        [ 9.,  0.,  0.],
        [10.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  1.,  0.],
        [ 2.,  1.,  0.],
        [ 3.,  1.,  0.],
        [ 4.,  1.,  0.],
        [ 5.,  1.,  0.],
        [ 6.,  1.,  0.],
        [ 7.,  1.,  0.],
        [ 8.,  1.,  0.],
        [ 9.,  1.,  0.],
        [10.,  1.,  0.],
        [ 0.,  2.,  0.],
        [ 1.,  2.,  0.],
        [ 2.,  2.,  0.],
        [ 3.,  2.,  0.],
        [ 4.,  2.,  0.],
        [ 5.,  2.,  0.],
        [ 6.,  2.,  0.],
        [ 7.,  2.,  0.],
        [ 8.,  2.,  0.],
        [ 9.,  2.,  0.],
        [10.,  2.,  0.],
        [ 0.,  3.,  0.],
        [ 1.,  3.,  0.],
        [ 2.,  3.,  0.],
        [ 3.,  3.,  0.],
        [ 4.,  3.,  0.],
        [ 5.,  3.,  0.],
        [ 6.,  3.,  0.],


In [14]:
imgpoints

[array([[[1009.3044 ,  446.37698]],
 
        [[1080.2369 ,  473.57663]],
 
        [[1150.2701 ,  500.5773 ]],
 
        [[1219.3706 ,  527.2389 ]],
 
        [[1287.5402 ,  553.59015]],
 
        [[1354.643  ,  579.5538 ]],
 
        [[1420.8647 ,  605.211  ]],
 
        [[1486.1284 ,  630.48694]],
 
        [[1550.4523 ,  655.4471 ]],
 
        [[1613.7998 ,  680.0644 ]],
 
        [[1676.1753 ,  704.3123 ]],
 
        [[ 982.8579 ,  519.1841 ]],
 
        [[1053.8578 ,  545.9412 ]],
 
        [[1124.1338 ,  572.436  ]],
 
        [[1193.2844 ,  598.564  ]],
 
        [[1261.5508 ,  624.4598 ]],
 
        [[1328.8777 ,  649.7991 ]],
 
        [[1395.1912 ,  674.9573 ]],
 
        [[1460.5359 ,  699.7246 ]],
 
        [[1524.9382 ,  724.1674 ]],
 
        [[1588.4379 ,  748.26807]],
 
        [[1650.875  ,  771.9932 ]],
 
        [[ 956.5615 ,  591.9537 ]],
 
        [[1027.7312 ,  618.244  ]],
 
        [[1098.0454 ,  644.20465]],
 
        [[1167.3763 ,  669.7949 ]],
 
        [[12

In [15]:
cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

(0.055280045711773224,
 array([[2.51871226e+03, 0.00000000e+00, 1.08045518e+03],
        [0.00000000e+00, 2.51898572e+03, 8.10445150e+02],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]),
 array([[-7.73529233e-02,  1.60282894e-01,  7.23371903e-05,
          1.75367878e-03, -4.47502729e-01]]),
 (array([[ 0.08408605],
         [-0.22289696],
         [ 0.34257825]]),
  array([[-0.13263158],
         [ 0.03787585],
         [ 0.08311908]])),
 (array([[-0.92128639],
         [-4.70643807],
         [32.50237739]]),
  array([[-1.45624132],
         [-3.14147107],
         [36.32171909]])))

In [16]:
import matplotlib.pyplot as plt

In [17]:
R = cv.Rodrigues(rvecs[0])[0]

In [18]:
tvec = tvecs[0].squeeze()

In [19]:
H = np.dot(mtx, np.concatenate((R[:,:2], tvec[:,None]), axis = 1) )/tvec[-1] 

In [20]:
R

array([[ 0.91768338, -0.34195928, -0.20228956],
       [ 0.32348712,  0.93868232, -0.11929619],
       [ 0.23068007,  0.04403806,  0.97203259]])

In [21]:
H

array([[ 7.87825404e+01, -2.50355801e+01,  1.00906178e+03],
       [ 3.08227602e+01,  7.38474534e+01,  4.45688747e+02],
       [ 7.09732922e-03,  1.35491809e-03,  1.00000000e+00]])

In [22]:
corners

array([[[ 979.62915,  592.7919 ]],

       [[1048.5057 ,  597.94507]],

       [[1117.7013 ,  603.28406]],

       [[1187.0565 ,  608.66907]],

       [[1256.5367 ,  613.9695 ]],

       [[1326.0482 ,  619.4644 ]],

       [[1395.795  ,  624.9137 ]],

       [[1465.6465 ,  630.35016]],

       [[1535.518  ,  635.7168 ]],

       [[1605.4448 ,  641.28705]],

       [[1675.4097 ,  646.8596 ]],

       [[ 973.2992 ,  660.6599 ]],

       [[1042.3809 ,  665.9693 ]],

       [[1111.8807 ,  671.3873 ]],

       [[1181.4454 ,  676.98206]],

       [[1251.2025 ,  682.40027]],

       [[1321.0782 ,  687.7247 ]],

       [[1391.0511 ,  693.29877]],

       [[1461.0896 ,  698.9029 ]],

       [[1531.2657 ,  704.4069 ]],

       [[1601.4307 ,  709.93   ]],

       [[1671.622  ,  715.5236 ]],

       [[ 966.87286,  729.0249 ]],

       [[1036.3387 ,  734.5553 ]],

       [[1106.0409 ,  740.0329 ]],

       [[1175.9144 ,  745.59644]],

       [[1245.8661 ,  751.1587 ]],

       [[1315.9698 ,  756.66

In [23]:
corners2

array([[[ 979.62915,  592.7919 ]],

       [[1048.5057 ,  597.94507]],

       [[1117.7013 ,  603.28406]],

       [[1187.0565 ,  608.66907]],

       [[1256.5367 ,  613.9695 ]],

       [[1326.0482 ,  619.4644 ]],

       [[1395.795  ,  624.9137 ]],

       [[1465.6465 ,  630.35016]],

       [[1535.518  ,  635.7168 ]],

       [[1605.4448 ,  641.28705]],

       [[1675.4097 ,  646.8596 ]],

       [[ 973.2992 ,  660.6599 ]],

       [[1042.3809 ,  665.9693 ]],

       [[1111.8807 ,  671.3873 ]],

       [[1181.4454 ,  676.98206]],

       [[1251.2025 ,  682.40027]],

       [[1321.0782 ,  687.7247 ]],

       [[1391.0511 ,  693.29877]],

       [[1461.0896 ,  698.9029 ]],

       [[1531.2657 ,  704.4069 ]],

       [[1601.4307 ,  709.93   ]],

       [[1671.622  ,  715.5236 ]],

       [[ 966.87286,  729.0249 ]],

       [[1036.3387 ,  734.5553 ]],

       [[1106.0409 ,  740.0329 ]],

       [[1175.9144 ,  745.59644]],

       [[1245.8661 ,  751.1587 ]],

       [[1315.9698 ,  756.66

In [24]:
transformedCorners = cv2.perspectiveTransform(corners, H)

In [25]:
transformedCorners

array([[[ 7234.618 ,  8499.005 ]],

       [[ 7419.467 ,  8314.123 ]],

       [[ 7585.654 ,  8148.364 ]],

       [[ 7735.8916,  7998.6035]],

       [[ 7872.713 ,  7861.9746]],

       [[ 7996.8057,  7738.5264]],

       [[ 8110.887 ,  7624.886 ]],

       [[ 8215.828 ,  7520.3037]],

       [[ 8312.723 ,  7423.586 ]],

       [[ 8401.786 ,  7335.0996]],

       [[ 8484.376 ,  7253.0435]],

       [[ 6946.301 ,  9000.775 ]],

       [[ 7145.624 ,  8790.418 ]],

       [[ 7325.462 ,  8600.822 ]],

       [[ 7487.3794,  8430.542 ]],

       [[ 7635.2866,  8274.543 ]],

       [[ 7770.5923,  8131.605 ]],

       [[ 7893.8022,  8001.963 ]],

       [[ 8006.954 ,  7882.955 ]],

       [[ 8111.707 ,  7772.56  ]],

       [[ 8208.445 ,  7670.6504]],

       [[ 8297.966 ,  7576.4688]],

       [[ 6658.792 ,  9501.035 ]],

       [[ 6872.8354,  9265.125 ]],

       [[ 7066.0005,  9052.056 ]],

       [[ 7240.596 ,  8859.633 ]],

       [[ 7399.1963,  8684.823 ]],

       [[ 7544.2246,  8524.8

In [26]:
img1 = cv2.imread('1.bmp', 0)
img2 = cv2.imread('2.bmp', 0)

In [27]:
img2 = cv2.polylines(img2, [np.int32(transformedCorners)], True, (255, 255, 255), 2, cv2.LINE_AA)

In [28]:
cv2.imshow('img2', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'result' is not defined

In [ ]:
cv2.imshow('Homography Certification', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
dst = cv.perspectiveTransform(corners,M)
img2 = cv.polylines(img2,[np.int32(dst)],True,255,3, cv.LINE_AA)

NameError: name 'M' is not defined

In [30]:
corners

array([[[ 979.62915,  592.7919 ]],

       [[1048.5057 ,  597.94507]],

       [[1117.7013 ,  603.28406]],

       [[1187.0565 ,  608.66907]],

       [[1256.5367 ,  613.9695 ]],

       [[1326.0482 ,  619.4644 ]],

       [[1395.795  ,  624.9137 ]],

       [[1465.6465 ,  630.35016]],

       [[1535.518  ,  635.7168 ]],

       [[1605.4448 ,  641.28705]],

       [[1675.4097 ,  646.8596 ]],

       [[ 973.2992 ,  660.6599 ]],

       [[1042.3809 ,  665.9693 ]],

       [[1111.8807 ,  671.3873 ]],

       [[1181.4454 ,  676.98206]],

       [[1251.2025 ,  682.40027]],

       [[1321.0782 ,  687.7247 ]],

       [[1391.0511 ,  693.29877]],

       [[1461.0896 ,  698.9029 ]],

       [[1531.2657 ,  704.4069 ]],

       [[1601.4307 ,  709.93   ]],

       [[1671.622  ,  715.5236 ]],

       [[ 966.87286,  729.0249 ]],

       [[1036.3387 ,  734.5553 ]],

       [[1106.0409 ,  740.0329 ]],

       [[1175.9144 ,  745.59644]],

       [[1245.8661 ,  751.1587 ]],

       [[1315.9698 ,  756.66

In [31]:
pts1 = corners.reshape(-1,1,2).astype(np.float32)
dst1 = cv2.perspectiveTransform(pts1, H)

In [32]:
print(pts1)

[[[ 979.62915  592.7919 ]]

 [[1048.5057   597.94507]]

 [[1117.7013   603.28406]]

 [[1187.0565   608.66907]]

 [[1256.5367   613.9695 ]]

 [[1326.0482   619.4644 ]]

 [[1395.795    624.9137 ]]

 [[1465.6465   630.35016]]

 [[1535.518    635.7168 ]]

 [[1605.4448   641.28705]]

 [[1675.4097   646.8596 ]]

 [[ 973.2992   660.6599 ]]

 [[1042.3809   665.9693 ]]

 [[1111.8807   671.3873 ]]

 [[1181.4454   676.98206]]

 [[1251.2025   682.40027]]

 [[1321.0782   687.7247 ]]

 [[1391.0511   693.29877]]

 [[1461.0896   698.9029 ]]

 [[1531.2657   704.4069 ]]

 [[1601.4307   709.93   ]]

 [[1671.622    715.5236 ]]

 [[ 966.87286  729.0249 ]]

 [[1036.3387   734.5553 ]]

 [[1106.0409   740.0329 ]]

 [[1175.9144   745.59644]]

 [[1245.8661   751.1587 ]]

 [[1315.9698   756.66974]]

 [[1386.2279   762.39716]]

 [[1456.5326   767.93256]]

 [[1526.9762   773.4811 ]]

 [[1597.4554   779.1859 ]]

 [[1667.8503   784.87787]]

 [[ 960.4539   798.0019 ]]

 [[1030.1656   803.5189 ]]

 [[1100.0498   809.2

In [33]:
print(dst1)

[[[ 7234.618   8499.005 ]]

 [[ 7419.467   8314.123 ]]

 [[ 7585.654   8148.364 ]]

 [[ 7735.8916  7998.6035]]

 [[ 7872.713   7861.9746]]

 [[ 7996.8057  7738.5264]]

 [[ 8110.887   7624.886 ]]

 [[ 8215.828   7520.3037]]

 [[ 8312.723   7423.586 ]]

 [[ 8401.786   7335.0996]]

 [[ 8484.376   7253.0435]]

 [[ 6946.301   9000.775 ]]

 [[ 7145.624   8790.418 ]]

 [[ 7325.462   8600.822 ]]

 [[ 7487.3794  8430.542 ]]

 [[ 7635.2866  8274.543 ]]

 [[ 7770.5923  8131.605 ]]

 [[ 7893.8022  8001.963 ]]

 [[ 8006.954   7882.955 ]]

 [[ 8111.707   7772.56  ]]

 [[ 8208.445   7670.6504]]

 [[ 8297.966   7576.4688]]

 [[ 6658.792   9501.035 ]]

 [[ 6872.8354  9265.125 ]]

 [[ 7066.0005  9052.056 ]]

 [[ 7240.596   8859.633 ]]

 [[ 7399.1963  8684.823 ]]

 [[ 7544.2246  8524.841 ]]

 [[ 7676.5825  8379.239 ]]

 [[ 7798.751   8244.474 ]]

 [[ 7911.5225  8120.0786]]

 [[ 8015.387   8005.7764]]

 [[ 8111.566   7899.9224]]

 [[ 6372.0337 10000.122 ]]

 [[ 6601.141   9737.747 ]]

 [[ 6806.896   9502.

In [34]:
import matplotlib.pyplot as plt

In [35]:
imageread = cv2.imread('2.bmp') 

In [36]:
imagegray = cv2.cvtColor(imageread, cv2.COLOR_BGR2GRAY)

In [37]:
output_image = cv2.drawKeypoints(imagegray, dst1, 0, (0, 0, 255), 
                                 flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'drawKeypoints'
> Overload resolution failed:
>  - Can't parse 'keypoints'. Sequence item with index 0 has a wrong type
>  - Can't parse 'keypoints'. Sequence item with index 0 has a wrong type


In [38]:
imagegray = cv2.polylines(imagegray, [np.int32(dst1)], True, (255, 255, 255), 2, cv2.LINE_AA)

In [39]:
imageread1 = cv2.imread('1.bmp') 

In [40]:
imagegray1 = cv2.cvtColor(imageread1, cv2.COLOR_BGR2GRAY)

In [41]:
drawParameters = dict(matchColor=(0, 255, 0), singlePointColor=None, matchesMask=matchesMask, flags=2)

NameError: name 'matchesMask' is not defined

In [42]:
drawParameters = dict(matchColor=(0, 255, 0), singlePointColor=None, matchesMask=None, flags=2)

In [47]:
result = cv2.drawMatches(imagegray1, corners, imagegray, dst1)

error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'drawMatches'
> Overload resolution failed:
>  - drawMatches() missing required argument 'matches1to2' (pos 5)
>  - drawMatches() missing required argument 'matches1to2' (pos 5)
>  - drawMatches() missing required argument 'matches1to2' (pos 5)
>  - drawMatches() missing required argument 'matches1to2' (pos 5)


In [48]:
corners

array([[[ 979.62915,  592.7919 ]],

       [[1048.5057 ,  597.94507]],

       [[1117.7013 ,  603.28406]],

       [[1187.0565 ,  608.66907]],

       [[1256.5367 ,  613.9695 ]],

       [[1326.0482 ,  619.4644 ]],

       [[1395.795  ,  624.9137 ]],

       [[1465.6465 ,  630.35016]],

       [[1535.518  ,  635.7168 ]],

       [[1605.4448 ,  641.28705]],

       [[1675.4097 ,  646.8596 ]],

       [[ 973.2992 ,  660.6599 ]],

       [[1042.3809 ,  665.9693 ]],

       [[1111.8807 ,  671.3873 ]],

       [[1181.4454 ,  676.98206]],

       [[1251.2025 ,  682.40027]],

       [[1321.0782 ,  687.7247 ]],

       [[1391.0511 ,  693.29877]],

       [[1461.0896 ,  698.9029 ]],

       [[1531.2657 ,  704.4069 ]],

       [[1601.4307 ,  709.93   ]],

       [[1671.622  ,  715.5236 ]],

       [[ 966.87286,  729.0249 ]],

       [[1036.3387 ,  734.5553 ]],

       [[1106.0409 ,  740.0329 ]],

       [[1175.9144 ,  745.59644]],

       [[1245.8661 ,  751.1587 ]],

       [[1315.9698 ,  756.66

In [50]:
dst1

array([[[ 7234.618 ,  8499.005 ]],

       [[ 7419.467 ,  8314.123 ]],

       [[ 7585.654 ,  8148.364 ]],

       [[ 7735.8916,  7998.6035]],

       [[ 7872.713 ,  7861.9746]],

       [[ 7996.8057,  7738.5264]],

       [[ 8110.887 ,  7624.886 ]],

       [[ 8215.828 ,  7520.3037]],

       [[ 8312.723 ,  7423.586 ]],

       [[ 8401.786 ,  7335.0996]],

       [[ 8484.376 ,  7253.0435]],

       [[ 6946.301 ,  9000.775 ]],

       [[ 7145.624 ,  8790.418 ]],

       [[ 7325.462 ,  8600.822 ]],

       [[ 7487.3794,  8430.542 ]],

       [[ 7635.2866,  8274.543 ]],

       [[ 7770.5923,  8131.605 ]],

       [[ 7893.8022,  8001.963 ]],

       [[ 8006.954 ,  7882.955 ]],

       [[ 8111.707 ,  7772.56  ]],

       [[ 8208.445 ,  7670.6504]],

       [[ 8297.966 ,  7576.4688]],

       [[ 6658.792 ,  9501.035 ]],

       [[ 6872.8354,  9265.125 ]],

       [[ 7066.0005,  9052.056 ]],

       [[ 7240.596 ,  8859.633 ]],

       [[ 7399.1963,  8684.823 ]],

       [[ 7544.2246,  8524.8

In [51]:
print(dst1)

[[[ 7234.618   8499.005 ]]

 [[ 7419.467   8314.123 ]]

 [[ 7585.654   8148.364 ]]

 [[ 7735.8916  7998.6035]]

 [[ 7872.713   7861.9746]]

 [[ 7996.8057  7738.5264]]

 [[ 8110.887   7624.886 ]]

 [[ 8215.828   7520.3037]]

 [[ 8312.723   7423.586 ]]

 [[ 8401.786   7335.0996]]

 [[ 8484.376   7253.0435]]

 [[ 6946.301   9000.775 ]]

 [[ 7145.624   8790.418 ]]

 [[ 7325.462   8600.822 ]]

 [[ 7487.3794  8430.542 ]]

 [[ 7635.2866  8274.543 ]]

 [[ 7770.5923  8131.605 ]]

 [[ 7893.8022  8001.963 ]]

 [[ 8006.954   7882.955 ]]

 [[ 8111.707   7772.56  ]]

 [[ 8208.445   7670.6504]]

 [[ 8297.966   7576.4688]]

 [[ 6658.792   9501.035 ]]

 [[ 6872.8354  9265.125 ]]

 [[ 7066.0005  9052.056 ]]

 [[ 7240.596   8859.633 ]]

 [[ 7399.1963  8684.823 ]]

 [[ 7544.2246  8524.841 ]]

 [[ 7676.5825  8379.239 ]]

 [[ 7798.751   8244.474 ]]

 [[ 7911.5225  8120.0786]]

 [[ 8015.387   8005.7764]]

 [[ 8111.566   7899.9224]]

 [[ 6372.0337 10000.122 ]]

 [[ 6601.141   9737.747 ]]

 [[ 6806.896   9502.

In [3]:
import cv2
imagenew = cv2.circle(imagegray, dst1, radius=0, color=(0, 0, 255), thickness=-1)
cv2.imshow('danying image',imagenew)

NameError: name 'imagegray' is not defined

In [1]:
dist1

NameError: name 'dist1' is not defined

In [2]:
dst1

NameError: name 'dst1' is not defined